### ISSUE TITLE
Error when using angular universal

### ISSUE THREAD

**Issue by steveacalabro** [fetrarij/ngx-daterangepicker-material#143]
Hello,

I came across an error when using this component inside of an ssr build using angular universal. For my use case, I simply used the example simple code. It builds fine when using non-SSR, however, when you try it with it you get the following error.

command
```
npm run build:ssr && npm run serve:ssr 
```

error
```
/Users/{user}/_git/{project}/web/dist/server.js:263990
        Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [Object, HTMLElement]),
                                                                                               ^

ReferenceError: HTMLElement is not defined
    at /Users/{user}/_git/{project}/web/dist/server.js:263990:96
    at Module.<anonymous> (/Users/{user}/_git/{project}/web/dist/server.js:264017:2)
    at __webpack_require__ (/Users/{user}/_git/{project}/web/dist/server.js:20:30)
    at Object.ngx-daterangepicker-material (/Users/{user}/_git/{project}/web/dist/server.js:139940:18)
    at __webpack_require__ (/Users/{user}/_git/{project}/web/dist/server.js:131462:30)
    at Module../node_modules/ngx-daterangepicker-material/ngx-daterangepicker-material.ngfactory.js (/Users/{user}/_git/{project}/web/dist/server.js:136634:86)
    at __webpack_require__ (/Users/{user}/_git/{project}/web/dist/server.js:131462:30)
    at Module../src/app/app.server.module.ngfactory.js (/Users/{user}/_git/{project}/web/dist/server.js:137492:139)
    at __webpack_require__ (/Users/{user}/_git/{project}/web/dist/server.js:131462:30)
    at Module../src/main.server.ts (/Users/{user}/_git/{project}/web/dist/server.js:139196:90)
```

**Comment by Jorgen-VikingGod** [comment]
have the same issue and can not use this changes - because there is no release with this changes inside...
Any idea, how I can use this commit in my package.json

**Comment by fetrarij** [comment]
hello, v2.1.2 is up. Thanks
