### ISSUE TITLE
Error ng build --prod

### ISSUE THREAD

**Issue by castor-dev3** [fetrarij/ngx-daterangepicker-material#228]
After a fresh install i've received this error while building.

> ERROR in ./node_modules/ngx-daterangepicker-material/fesm5/ngx-daterangepicker-material.js
> Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
> TypeError: Cannot read property 'kind' of undefined
>     at isAngularDecoratorMetadataExpression (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
>     at checkNodeForDecorators (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)    
>     at visitNodes (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)    at Object.forEachChild (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
>     at checkNodeForDecorators (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)    
>     at visitNode (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24) 
>     at Object.forEachChild (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
>     at checkNodeForDecorators (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)    
>     at visitNode (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24) 
>     at Object.forEachChild (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
>     at checkNodeForDecorators (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)    
>     at visitNode (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
>     at Object.forEachChild (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
>     at checkNodeForDecorators (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)    
>     at visitNode (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24) 
>     at Object.forEachChild (D:\Projects\castor\o2c-frontend-2\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)

After checking a few things i've made a downgrade from ngx-daterangepicker-material 2.1.11 to 2.1.10 and the problem was gone.

**Comment by camillewall** [comment]
The "cannot read property 'kind' of undefined" error still exists in version 2.2.0. I agree with @castor-dev3 that version 2.1.10 builds correctly with --prod.

**Comment by yudarik** [comment]
I'm experiencing the same issue with angular@8.2.0 and ngx-daterangepicker-material@2.2.1
Downgraded to 2.1.10, but the same issue is still reproduced.
The interesting thing is that it only reproduced when building with --stats-json flag.
Building alone with --prod flag only, works fine on the most recent version (2.2.0) of the module as well.

**Comment by Timebutt** [comment]
A new major version `3.0.0` was released, could you verify if that addresses this issue? I haven't seen this issue when I build with the `--stats-json` flag for instance, so not sure if this is still a problem.

**Comment by Aashir1** [comment]
> I'm experiencing the same issue with angular@8.2.0 and ngx-daterangepicker-material@2.2.0
> Downgraded to 2.1.10, but the same issue is still reproduced.
> The interesting thing is that it only reproduced when building with --stats-json flag.
> Building alone with --prod flag only, works fine on 2.1.10, but not with 2.2.0

But couple of features are missing in  2.1.10.

**Comment by Aashir1** [comment]
2.1.11 also working very well will --prod flag.

**Comment by apasanghamitrai** [comment]
I had the same issue when using Angular v5.2.0, where only  2.1.10 worked with the ng build --prod flag. While the latest 2.4.1 for Angular < 9.0.0 didn't work.
